version: "3.2"
  
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: social_media_database
    volumes:
      - ./mongo/data:/data
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
      - 27018:27018
